before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ByPAt02/XZlSCTpze0xcX9Jz88X6RTLdflXeL2DLY7E/3S/uCxeA+Fe+iBvALpTrM95hqF49gJWEVsYUZn+9i5v/NyC1Te5zzLWKncvwxxShDazNYxpMARnTl3TorZrOakMlJBbIXjKc0cIu4zki7d7wWI1xOVZOFNJDByC8gpH5f0YBoOsn+6KbQbbD6MMD/3s8rcGaRTqKdUuH0etR+Ac4hU0MnebTdgD4SOm8iqyMFkVqZhRruqibeNnaGSDOffCVqZJaVe/OTAsvpqRrJGtqjpY9Gav41vDZ6NMIfL1/thX5C9CjH2hogjC8uc+ZD7I7buTOAH5nOKjoP3Muw9D/1DYUlM5he9gjzR9+cMvH+u+ryX1fNUtKe6DlqGwYxbqhCatFyU+w8OM1ga/KCx/kKKOu9sgtOdIGGNAoltbQhF+g3mVVhcT3WfGmDF8xFOJqxHhzwLUwuUc8dAcZepjm9xXG8697g2B2umG8KEqrxe1OXVC21HtCVnsxmg1Vcm9TNPis/yBnp+v6apVK6GcGmAB94t/6K+8M5kx+rT8edGJo/2nom3vY1XuDPary78bE+VzGxy00SuRcFO/yyrbmQDhJ05twGjeF6R2CQ8GQE1FnldeJUePFXRgIO49Nzlx+zn9kQ+zXUYAGcfZjomZXiiI4r5sOSu/EHxqgZOE= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
